name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v3
      - name: Install dependencies
        run: uv sync --all-groups
      - name: Ruff lint
        run: uv run ruff check src/orcheo packages/sdk/src tests
      - name: Ruff format check
        run: uv run ruff format . --check
      - name: MyPy
        run: uv run mypy src/orcheo packages/sdk/src --install-types --non-interactive
      - name: Pytest with coverage
        run: uv run pytest --cov=orcheo --cov=orcheo_sdk --cov-report=xml
      - name: Diff coverage
        run: uv run diff-cover coverage.xml --compare-branch=origin/main --fail-under=100

  canvas:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/canvas
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test -- --run
